version : '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
        - db 
    environment:
      - "DJANGO_SECRET_KEY=15y650pz*!63qcf_%^5@3sl!2g^2dio1y(y)mwk0%o%*#q312y"

  db:
    image: postgres:11
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  
  postgres_data:
